#!/usr/bin/env bash

################################################################################
top=$(realpath "$(dirname "$0")/..")

################################################################################
# So other scripts can access the bin directory:
export HLWMRC_BIN="$top/bin"

################################################################################
function hc() {
  herbstclient "$@"
}

################################################################################
hc emit_hook reload

################################################################################
# Restore the cursor that was previously set in ~/.xsession:
# https://github.com/herbstluftwm/herbstluftwm/issues/1345
set_cursor_cmd=$(grep xsetroot ~/.xsession | head -1)

if [ -n "$set_cursor_cmd" ]; then
  eval "$set_cursor_cmd"
fi

################################################################################
workspaces=(
  scratch
  browsers
  chat
  mail
  rc
  rfa
  rip
  music
  monitoring
)

hc try silent rename default scratch

for workspace in "${workspaces[@]}"; do
  hc add "$workspace"
done

################################################################################
# shellcheck source=keys
. "$top/config/keys"

# shellcheck source=theme
. "$top/config/theme"

################################################################################
# Basic settings:
hc set always_show_frame on
hc set auto_detect_monitors on
hc set auto_detect_panels on
hc set focus_crosses_monitor_boundaries off
hc set focus_follows_mouse on
hc set focus_stealing_prevention on
hc set gapless_grid on
hc set hide_covered_windows on
hc set raise_on_focus_temporarily on
hc set smart_frame_surroundings on
hc set smart_window_surroundings off
hc set swap_monitors_to_get_tag on
hc set update_dragged_clients on

################################################################################
# Initial monitor settings:
hc detect_monitors

# Add a little extra padding on the primary monitor for the panel:
hc attr monitors.0.pad_up 26

################################################################################
# Window rules:
hc unrule -F
hc rule floatplacement=center focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG'
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="Pinentry" floating=on

################################################################################
hc unlock

################################################################################
# Start hook scripts:
"$top/bin/hlwm-ffm-skip-floats.sh" &
