#!/usr/bin/env bash

################################################################################
top=$(realpath "$(dirname "$0")/..")

################################################################################
# So other scripts can access the bin directory:
export HLWMRC_BIN="$top/bin"

################################################################################
function hc() {
  herbstclient "$@"
}

################################################################################
hc emit_hook reload

################################################################################
# Restore the cursor that was previously set in ~/.xsession:
# https://github.com/herbstluftwm/herbstluftwm/issues/1345
set_cursor_cmd=$(grep xsetroot ~/.hm-xsession | head -1)

if [ -n "$set_cursor_cmd" ]; then
  eval "$set_cursor_cmd"
fi

################################################################################
workspaces=(
  GTD      # 1
  Social   # 2
  Hacking  # 3
  Media    # 4
  Meetings # 5
  School   # 6
  RFA1     # 7
  RFA2     # 8
  Spare    # 9
  Web      # 0
)

hc try silent rename default "${workspaces[0]}"
for workspace in "${workspaces[@]}"; do
  hc add "$workspace"
done

################################################################################
# shellcheck source=keys
. "$top/config/keys"

# shellcheck source=theme
. "$top/config/theme"

################################################################################
# Basic settings:
hc set auto_detect_monitors on
hc set auto_detect_panels on
hc set focus_crosses_monitor_boundaries off
hc set focus_follows_mouse on
hc set focus_stealing_prevention on
hc set gapless_grid on
hc set hide_covered_windows on
hc set raise_on_focus_temporarily on
hc set show_frame_decorations if_empty
hc set smart_frame_surroundings on
hc set smart_window_surroundings off
hc set swap_monitors_to_get_tag on
hc set update_dragged_clients on

################################################################################
# Initial monitor settings:
hc detect_monitors

################################################################################
# Window rules:
hc unrule -F

# Default rule:
hc rule focus=on floatplacement=none

# Windows that shouldn't get the focus:
hc rule instance="popup" class="Emacs" focus=off

# Windows to float:
hc rule fixedsize floating=on
hc rule class~"[Pp]inentry" floating=on floatplacement=center
hc rule class="krdc" floating=on floatplacement=center
hc rule class="PrusaSlicer" floating=on floatplacement=center

# Plasma:
hc rule class="systemsettings" floating=on
hc rule class~"[Pp]lasma" floating=on
hc rule instance="plasmashell" class="plasmashell" manage=off

# Standard types:
hc rule \
  windowtype~'TYPE_(DIALOG|UTILITY|SPLASH)' \
  floating=on floatplacement=center

hc rule \
  windowtype~'TYPE_(NOTIFICATION|ON_SCREEN_DISPLAY|DOCK|DESKTOP)' \
  manage=off

################################################################################
hc unlock

################################################################################
# Start hook scripts:
"$top/bin/hlwm-ffm-skip-floats.sh" &
