#!/usr/bin/env bash

################################################################################
# For keysym names:
# https://cgit.freedesktop.org/xorg/proto/x11proto/tree/keysymdef.h

################################################################################
function kbd() {
  local key=$1
  shift

  hc keybind Mod4-"$key" "$@"
}

################################################################################
# Start from a clean slate:
hc keyunbind --all
hc mouseunbind --all

################################################################################
# Mouse:
hc mousebind Mod4-Button1 move
hc mousebind Mod4-Button2 zoom
hc mousebind Mod4-Button3 resize

################################################################################
# Windows and frames:
kbd k focus up
kbd j focus down
kbd l focus right
kbd h focus left

kbd Shift-k shift up
kbd Shift-j shift down
kbd Shift-l shift right
kbd Shift-h shift left

kbd Control-k resize up +0.02
kbd Control-j resize down +0.02
kbd Control-l resize right +0.02
kbd Control-j resize left +0.02

kbd Alt-k split top 0.5
kbd Alt-j split bottom 0.5
kbd Alt-l split right 0.5
kbd Alt-h split left 0.5
kbd s split auto 0.5
kbd Alt-s split explode

kbd m attr clients.focus.minimized true
kbd Shift-m jumpto last-minimized

kbd Shift-s attr clients.focus.pseudotile toggle
kbd semicolon spawn "$HLWMRC_BIN/hlwm-zoom.sh"
kbd F11 attr clients.focus.fullscreen toggle

kbd Tab cycle_all +1
kbd c cycle_frame
kbd q close_or_remove
kbd u jumpto urgent

################################################################################
# Layout and tweaks:
# kbd m set_layout max
# kbd g set_layout grid
# kbd h set_layout horizontal
# kbd v set_layout vertical

kbd BackSpace \
  or , and \
  . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max \
  , cycle_layout +1

# Toggle title bars:
kbd t \
  chain \
  - cycle_value theme.title_height 0 14 \
  - cycle_value theme.padding_top 0 2

# Use a predefined layout:
kbd Alt-1 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 1
kbd Alt-2 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 2
kbd Alt-3 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 3

################################################################################
# Tags (workspaces/desktops):
kbd apostrophe use_previous

tag_indexes=({1..9} 0)

for index in "${tag_indexes[@]}"; do
  kbd "$index" use_index "$((index - 1))"
done

################################################################################
# Monitors:
kbd b spawn "$HLWMRC_BIN/hlwm-scratchpads.sh" browser-sidebar
kbd a spawn "$HLWMRC_BIN/hlwm-scratchpads.sh" notes
# FIXME: kbd j spawn "$HLWMRC_BIN/hlwm-scratchpads.sh" scratch
kbd period focus_monitor +1
kbd comma focus_monitor -1

kbd d \
  substitute MON monitors.focus.index chain \
  + lock \
  + focus_monitor +1 \
  + substitute TAG monitors.focus.tag chain \
  - focus_monitor MON \
  - use TAG \
  - unlock

################################################################################
# Audio keys:
hc keybind XF86AudioPlay spawn player-mpris-tail play-pause
hc keybind XF86AudioPrev spawn player-mpris-tail previous
hc keybind XF86AudioNext spawn player-mpris-tail next
hc keybind XF86Launch6 spawn paswitch
hc keybind XF86AudioLowerVolume spawn pamixer --decrease 5
hc keybind XF86AudioRaiseVolume spawn pamixer --increase 5
hc keybind XF86AudioMute spawn pamixer --toggle-mute
# kbd XF86Launch7 radioPrompt

################################################################################
# Launching things:
kbd e spawn e -c
kbd Return spawn konsole
kbd Shift-Return spawn konsole -e zsh
kbd r spawn rofi -show drun
kbd o spawn rofi -show windowcd -modi window,windowcd
kbd Shift-o spawn rofi -show window -modi window,windowcd
kbd grave spawn rofi-pass.sh
kbd F12 spawn polybar-msg cmd toggle
kbd Shift-1 spawn "$HLWMRC_BIN/hlwm-launch.sh"
kbd space spawn "$HLWMRC_BIN/hlwm-rofi-combi.sh"

# Lock the screen:
# FIXME: hc keybind Control-Alt-l spawn loginctl lock-session
