#!/usr/bin/env bash

################################################################################
# For keysym names:
# https://cgit.freedesktop.org/xorg/proto/x11proto/tree/keysymdef.h

################################################################################
function kbd() {
  local key=$1
  shift

  hc keybind Mod4-"$key" "$@"
}

################################################################################
# Start from a clean slate:
hc keyunbind --all
hc mouseunbind --all

################################################################################
# Mouse:
hc mousebind Mod4-Button1 move
hc mousebind Mod4-Button2 zoom
hc mousebind Mod4-Button3 resize

################################################################################
# Windows and frames:

# Move keyboard focus to another window:
kbd k focus up
kbd j focus down
kbd l focus right
kbd h focus left

# Move current window to another position:
kbd Shift-k shift --level=all up
kbd Shift-j shift --level=all down
kbd Shift-l shift --level=all right
kbd Shift-h shift --level=all left

# Resize the current window:
kbd Control-k resize up +0.02
kbd Control-j resize down +0.02
kbd Control-l resize right +0.02
kbd Control-h resize left +0.02

kbd Control-Shift-k resize up -0.02
kbd Control-Shift-j resize down -0.02
kbd Control-Shift-l resize right -0.02
kbd Control-Shift-h resize left -0.02

# Split the current frame:
kbd Alt-k split top 0.5
kbd Alt-j split bottom 0.5
kbd Alt-l split right 0.5
kbd Alt-h split left 0.5

kbd s split auto 0.5
kbd Alt-s split explode

# Minimize and restore windows:
kbd m attr clients.focus.minimized true
kbd Shift-m jumpto last-minimized

# Toggle various features:
kbd t attr clients.focus.floating toggle
kbd Shift-t attr clients.focus.pseudotile toggle
kbd c spawn "$HLWMRC_BIN/hlwm-zoom.sh"
kbd F11 attr clients.focus.fullscreen toggle

# Cycle:
kbd grave cycle
kbd Tab cycle

kbd q close_or_remove
kbd u jumpto urgent

# Focus the last floating window on the current tag:
kbd r \
  foreach CLIENT clients. \
  sprintf FLOATING "%c.floating" CLIENT \
  sprintf TAG "%{%c.tag}" CLIENT try and \
  , compare FLOATING = true \
  , compare tags.focus.name = TAG \
  , sprintf WID "%{%c.winid}" CLIENT jumpto WID

################################################################################
# Layout and tweaks:
kbd g set_layout grid
kbd f set_layout max

# Cycle layouts:
kbd BackSpace \
  or , and \
  . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max \
  , cycle_layout +1

# Use a predefined layout:
kbd Alt-0 spawn "$HLWMRC_BIN/hlwm-layout-reset.sh"
kbd Alt-1 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 1
kbd Alt-2 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 2
kbd Alt-3 spawn "$HLWMRC_BIN/hlwm-layout-columns.sh" 3

################################################################################
# Tags (workspaces/desktops):
kbd apostrophe use_previous
kbd Shift-period use_index --skip-visible +1
kbd Shift-comma use_index --skip-visible -1

tag_indexes=({1..10})

for index in "${tag_indexes[@]}"; do
  if [ "$index" -eq 10 ]; then
    key=0
  else
    key=$index
  fi

  # Switch to a tag:
  kbd "$key" use_index "$((index - 1))"

  # Move the focused window to another tag:
  kbd "Shift-$key" move_index "$((index - 1))"
done

################################################################################
# Monitors:
kbd period focus_monitor +1
kbd comma focus_monitor -1

kbd d \
  substitute MON monitors.focus.index \
  substitute SWAP settings.swap_monitors_to_get_tag chain \
  + lock \
  + attr settings.swap_monitors_to_get_tag on \
  + focus_monitor +1 \
  + substitute TAG monitors.focus.tag chain \
  - focus_monitor MON \
  - use TAG \
  - attr settings.swap_monitors_to_get_tag SWAP \
  - unlock

################################################################################
# Launching things:
kbd space spawn rofi-launcher.sh
kbd e spawn e -c
#kbd Return spawn konsole

# Lock the screen:
hc keybind Cancel spawn loginctl lock-session

# Control gromit-mpx:
hc keybind F7 spawn gromit-mpx --clear
hc keybind F8 spawn gromit-mpx-toggle.sh

# Audio keys:
hc keybind XF86AudioPlay spawn player-mpris-tail play-pause
hc keybind XF86AudioPrev spawn player-mpris-tail previous
hc keybind XF86AudioNext spawn player-mpris-tail next
hc keybind XF86Launch6 spawn paswitch
hc keybind XF86AudioLowerVolume spawn pamixer --decrease 5
hc keybind XF86AudioRaiseVolume spawn pamixer --increase 5
hc keybind XF86AudioMute spawn pamixer --toggle-mute
# kbd XF86Launch7 radioPrompt

# Screen Brightness:
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
