#!/usr/bin/env bash

################################################################################
# Gaps:
hc set window_gap 3
hc set frame_gap 0
hc set frame_padding 0

################################################################################
# Theme (colors and borders):
hc attr theme.reset 1
hc attr theme.border_width 2
hc attr theme.color "#474952ff"

hc attr theme.inner_width 2
hc attr theme.inner_color "#6c6d73ff"

hc attr theme.outer_width 0
hc attr theme.outer_color "#222632"

hc attr theme.active.color "#4e4267"
hc attr theme.active.inner_color "#735a97"

hc attr theme.urgent.color "#ca0b00ff"
hc attr theme.urgent.inner_color "#f32013ff"

hc attr theme.title_color "#aaaaaa00"
hc attr theme.active.title_color "#ffffff00"
hc attr theme.title_align center

if [ "$PLASMA_USE_QT_SCALING" -eq 1 ]; then
  font_size=6
  title_height=18
else
  font_size=10
  title_height=15
fi

hc attr theme.title_depth 8
hc attr theme.title_height "$title_height"
hc attr theme.title_font "FreeSans:size=$font_size"
hc attr theme.active.title_font "FreeSans:size=$font_size:style=Bold"

################################################################################
# Frame (colors and borders):
hc set frame_border_width 1
hc set frame_border_inner_width 1
hc set frame_transparent_width 2
hc set frame_bg_active_color "#000000ff"
hc set frame_bg_normal_color "#000000ff"
hc set frame_border_active_color "#ffffffff"
hc set frame_border_normal_color "#ddddddff"
hc set frame_border_inner_color "#ddddddff"
hc set frame_bg_transparent on
hc set frame_active_opacity 80
hc set frame_normal_opacity 20
