#!/usr/bin/env bash

################################################################################
# Gaps:
hc set window_gap 3
hc set frame_gap 2
hc set frame_padding -1

################################################################################
# Theme (colors and borders):
hc attr theme.reset 1
hc attr theme.border_width 0
hc attr theme.color "#444444aa"

hc attr theme.inner_width 2
hc attr theme.inner_color "#1f212a"

hc attr theme.outer_width 0
hc attr theme.outer_color "#222632"

hc attr theme.active.color "#b910cdaa"
hc attr theme.active.inner_color "#df00f7ff"

hc attr theme.urgent.color "#ca0b00ff"
hc attr theme.urgent.inner_color "#f32013ff"

hc attr theme.title_color "#ffffffff"
hc attr theme.active.title_color "#ffffff00"
hc attr theme.title_font "Hermit:pixelsize=11"
hc attr theme.title_align center
hc attr theme.title_height 15
hc attr theme.title_depth 8

################################################################################
# Frame (colors and borders):
hc set frame_border_width 1
hc set frame_border_inner_width 1
hc set frame_transparent_width 2
hc set frame_bg_active_color "#000000ff"
hc set frame_bg_normal_color "#000000ff"
hc set frame_border_active_color "#ffffffff"
hc set frame_border_normal_color "#ddddddff"
hc set frame_border_inner_color "#ddddddff"
hc set frame_bg_transparent on
hc set frame_active_opacity 80
hc set frame_normal_opacity 20
